#include <iostream>
using namespace std;
int main()
{
    // int n;
    // cin >> n;
    // if (cin >> n)
    // {
    //     cout << " Love Life ";
    // }
    // float principle , rate , time ;
    // cout << " principle = ";
    // cin >> principle ;
    // cout << " rate = " ;
    // cin >> rate ;
    // cout << " time = " ;
    // cin >> time ;

    // float si = ( principle * rate * time ) / 100 ;
    // cout << si ;
    // if (cout << n)
    // {
    //     cout << " Live Life ";
    // }
    // int a, b, swap = 0;
    // cout << "a = ";
    // cin >> a;
    // cout << "b = ";
    // cin >> b;
    // swap = b;
    // b = a;
    // a = swap;
    // cout << "a = " << a << " b = " << b;
    // int a ;
    // cout << "a = ";
    // cin >> a ; 
    // if ( a%2==0){
    //     cout << "even";
    // }
    // else{
    //     cout << "odd";
    // }
    int a , b ,c ;
    cout << "a = ";
    cin >> a ;
    cout << "b = ";
    cin >> b ;
    cout << "c = ";
    cin >> c ;
    if( a > b || a > c){
        if( b > c){
            cout << "b is greater";
        }
        else{
            cout << "c is greater";
        }
    }
    else if(b > c || b >> a){
        
    }
}